# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20170309_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='responder_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
