# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20170325_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='call_sid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
