# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20170507_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='Gender',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='Occupation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.Survey'),
        ),
    ]
