# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20170512_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Choice'),
        ),
        migrations.AddField(
            model_name='choice',
            name='weighting',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
