# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20170512_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='weighting',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
