# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20170722_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(b'TEXT', b'Text'), (b'SELECT ONE', b'Select one'), (b'INTEGER', b'Integer')], default=b'TEXT', max_length=50),
        ),
    ]
